--BULK INSERT: LOADING DATA FROM FILES TO TABLES ONLY .TEXT AND .CSV FILES CAN BE LOADED.
--SYNTAX FOR BULK INSERT

  BULK INSERT TABLE_NAME
  FROM 'C:\INPUTDATA.CSV'   --FILE LOCATION
  WITH (FIRSTROW = 2,
  FIELDTERMINATOR = ',',
  BATCHSIZE = 12000, -- IT IS USED TO INHANCE THE PERFORMANCE ON A SERVER 
  MAXERRORS = 2,     -- WHILE INSERTING THE DATA IF ERROR OCCURS IT WILL THROUGH(IT IS OPTIONAL)  
  ROWTERMINATOR = '\n')     --\n MEANS NEW ROW

--TOP CLAUSE IS USED TO SPECIFY THE NUMBER OF RECORDS TO RETURN. IT IS USED IN LARGE TABLES HAVING THOUSAND NUMBER OF RECORDS.

SELECT * FROM Sales.OrderDetails
SELECT TOP 50 * FROM Sales.OrderDetails

--CASE STATEMENT GOES THROUGH CONDITIONS AND RETURNS A VALUE WHEN FIRST CONDITION IS MET.

IF EXISTS(SELECT 2 FROM SYS.TABLES WHERE NAME = 'STUDENTS')
BEGIN 
  DROP TABLE STUDENTS
END

CREATE TABLE STUDENTS (
ID INT,
NAME VARCHAR(20),
GENDERID INT,
MARKS INT
)

INSERT INTO STUDENTS(ID,NAME,GENDERID,MARKS)
SELECT 1,'ABHI',1,450
UNION
SELECT 2,'ANNU',2,430
UNION
SELECT 3,'SAMMI',2,330
UNION
SELECT 4,'SAM',1, 280
UNION
SELECT 5,'SAHIL',1,320

--CASE
SELECT ID,NAME,CASE WHEN GENDERID = 1 THEN 'MALE' WHEN GENDERID = 2 THEN 'FEMALE' END GENDERNAME, MARKS,
CASE WHEN MARKS < 300 THEN '3RD DIVIDION'WHEN MARKS BETWEEN 300 AND  400 THEN '2ND DIVISION'WHEN
MARKS > 400 THEN '1ST DIVISION' 
END DIVISION
FROM STUDENTS

