--TYPES OF COMMANDS IN SQL SERVER
================================================
--DDL(DATA DEFINATION LANGUAGE):Used for dealing with structure of objects.using these command we can modify the objects.
--DDL COMMANDS ARE: 
                   -- CREATE
                   -- ALTER
		   -- DROP
		   -- RENAME
		   -- TRUNCATE
--DML(DATA MANIUPLATION LANGUAGE) : USED FOR MANAGING DATA STORED IN AN OBJECT.
--DDL COMMANDS ARE : --INSERT
                     --UPDATE
		     --DELETE
		     --MERGE
--DCL(DATA CENTROL LENGUAGE) : USED FOR SECURITY PURPOSES.USED TO PROVIDE ROLES,PERMISSIONS,ACCESS ETC.
--DCL COMMANDS ARE : --GRANT
                     --REVOKE
--TCL(TRANSACTION CONTROL LANGUAGE) : USED FOR MANAGING TRANSACTIONS IN SQL SERVER
--TCL COMMANDS ARE : --COMMIT
                     --ROLLBACK


IF EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME = 'STUDENTS_12')
    DROP TABLE STUDENTS_12
GO

CREATE TABLE STUDENTS_12(
ID INT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
BRANCH VARCHAR(10),
AGE INT CHECK(AGE>18),
JOINING DATE DEFAULT GETDATE() )

--TO ADD AND DELETE COLUMN IN A TABLE USE ALTER COMMAND
ALTER TABLE STUDENTS_12 
ADD EMAIL VARCHAR(30)

ALTER TABLE STUDENTS_12
DROP COLUMN NAME

--CHANGING LENGTH OF COLUMN USING ALTER COMMAND
ALTER TABLE STUDENTS_12
ALTER COLUMN BRANCH VARCHAR(40)

ALTER TABLE STUDENTS_12
ALTER COLUMN NAME VARCHAR(30)

--SP_HELP STUDENTS_12 TO FIND PROPERTIES OF TABLE

-- TO DROP COLUMN OR TABLE USE DROP COMMAND
DROP TABLE STUDENTS_12

ALTER TABLE STUDENTS_12
DROP COLUMN ID

--TO DROP COLUMN HAVING CONSTRAINTS FIRST WE NEED TO DROP CONSTRAINTS

ALTER TABLE STUDENTS_12
DROP CONSTRAINT CK__STUDENTS_12__AGE__4222D4EF

ALTER TABLE STUDENTS_12
DROP COLUMN AGE

SELECT * FROM STUDENTS_12

--RENAME A TABLE
EXEC sp_rename 'OLD TABLE NAME','NEW TABLE NAME'
EXEC sp_rename 'STUDENTS_12','CLG_STUDENTS'

--SP_HELP STUDENTS_12

--TRUNCATE IS USED TO DELETE RECORDS FROM TABLE 
TRUNCATE TABLE STUDENTS_12

====================================================
DML COMMANDS
INSERT
UPDATE 
DELETE

INSERT INTO STUDENTS_12(ID,NAME,BRANCH,AGE,EMAIL)
VALUES(1,'RAMU','IT',23,'abc@xyz.com')

INSERT INTO STUDENTS_12(ID,NAME,BRANCH,AGE,EMAIL,JOINING)
SELECT 2,'RASH', 'CSE',24,'rush@xyz.com','2019-05-12'

--WE CAN INSERT DATA IN A TABLE USING PROCEDURE 

ALTER PROCEDURE  GETDATA
AS
SELECT 3,'ANI','ECE',25,'smu@abc.com',GETDATE()

EXEC GETDATA

INSERT INTO STUDENTS_12(ID,NAME,BRANCH,AGE,EMAIL,JOINING)
EXEC GETDATA

SELECT * FROM STUDENTS

SP_HELP STUDENTS
--USING INSERT WE CAN ADD DATA FROM ONE TABLE TO OTHER
INSERT INTO STUDENTS(StudentID,Name,Age,JoinedDate)
SELECT ID,NAME,AGE,JOINING
FROM STUDENTS_12


TRUNCATE TABLE STUDENTS
