--DML Commands 

SELECT * FROM STUDENTS_12

UPDATE  STUDENTS_12
SET NAME = 'ANU'
WHERE ID = 3

UPDATE STUDENTS_12
SET BRANCH = 'CSE'
WHERE ID = 3

DELETE STUDENTS_12
WHERE ID = 3

INSERT INTO STUDENTS_12(ID,NAME,BRANCH,AGE,JOINING,EMAIL)
SELECT 3,'ANU','CSE',25,GETDATE(),'amu@abc.com'

---JOINS : JOINS ARE USED TO COMBINE 2 OR MORE TABLE 
-- TYPES OF JOINS ARE
-- INNER JOIN : RETURNS MATCHING RECORDS FROM TWO OR MORE TABLES.
-- LEFT JOIN : RETURNS ALL RECORDS FROM LEFT TABLE AND MATCHING VALUE FROM 2 OR MORE TABLE.
-- RIGHT JOIN : RETURNS ALL RECORDS FROM RIGHT TABLE AND MATCHING VALUE FROM 2 OR MORE TABLE.
-- FULL JOIN : RETURNS ALL THE RECORDS FROM BOTH TABLES MATCHING AS WELL AS NON MATCHING.
-- CROSS JOIN : COMBINES EACH ROW FROM FIRST TABLE WITH EACH ROW FROM SECOND TABLE.

SP_HELP GENDER 
ALTER TABLE GENDER
ALTER COLUMN NAME VARCHAR(10)

INSERT INTO GENDER (ID,NAME)
VALUES(3,'UNKNOWN')

SELECT * FROM GENDER
SELECT * FROM STUDENTS

UPDATE  STUDENTS
SET Gender = 'Female'
WHERE StudentID = 3


============================================
SP_HELP GENDER
SP_HELP STUDENTS
============================================
IF EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME  = 'EMP')
BEGIN
   DROP TABLE EMP
END

CREATE TABLE EMP(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(20) NOT NULL,
BRANCH VARCHAR(10),
GENDER VARCHAR(10),
AGE INT CHECK(AGE>18),
EMAIL VARCHAR(30),
BRANCHID INT FOREIGN KEY REFERENCES BRANCH(ID)
)

INSERT INTO EMP(NAME,BRANCH,GENDER,AGE,EMAIL)
VALUES('RAKESH','CSE','MALE',28,'rak@xyz.com'),
      ('SONI','ECE','FEMALE',24,'soni@xyz.com'),
	  ('DEEPAK','IT','MALE',23,'deepak@xyz.com'),
	  ('SHIKHA','CSE','FEMALE',22,'shikha@xyz.com'),
	  ('SAM','IT','MALE', 25,'sam@xyz.com'),
	  ('ANU','ECE','FEMALE',21,'anu@xyz.com')


IF EXISTS(SELECT 1 FROM SYS.TABLES WHERE NAME = 'BRANCH')
    DROP TABLE BRANCH

CREATE TABLE BRANCH(
ID INT PRIMARY KEY,
NAME VARCHAR(10)
)

INSERT INTO BRANCH(ID,NAME)
VALUES(1,'CSE'),(2,'ECE'),(3,'IT')

==============================================

UPDATE EMP
SET BRANCHID = 2
WHERE ID = 6


SELECT * FROM EMP
SELECT * FROM BRANCH

--INNER JOIN
SELECT E.NAME,E.BRANCH,E.GENDER,B.NAME,E.BRANCHID
FROM  EMP E
INNER JOIN BRANCH B 
ON E.ID = B.ID


--LEFT JOIN
SELECT E.NAME,E.BRANCH,E.GENDER,B.ID,E.BRANCHID
FROM  EMP E 
LEFT JOIN BRANCH B
ON E.ID = B.ID

--RIGHT JOIN
SELECT E.NAME,E.BRANCH,E.BRANCHID,E.GENDER,B.NAME
FROM EMP E  
RIGHT JOIN BRANCH B
ON E.ID = B.ID

--FULL JOIN 
SELECT E.NAME,E.BRANCH,E.BRANCHID,E.GENDER, B.NAME
FROM EMP E
FULL JOIN BRANCH B
ON E.ID = B.ID

--CROSS JOIN
SELECT E.NAME,E.BRANCH,E.BRANCHID,E.GENDER, B.NAME
FROM EMP E
CROSS JOIN BRANCH B

=========================================
SELECT * FROM Students
SELECT * FROM STUDENTS_12

--ADDING VALUES FROM ONETABLE TO OTHER TABLE
INSERT INTO Students(NAME,AGE)
SELECT NAME,AGE
FROM STUDENTS_12

SELECT * FROM GENDER
SELECT * FROM Students

--INNER JOINS 
SELECT S.NAME,S.GENDER,S.AGE,G.NAME
FROM Students S
INNER JOIN GENDER G
ON S.StudentID = G.ID 

--LEFT JOIN
SELECT S.NAME,S.GENDER,S.AGE,G.NAME
FROM GENDER G
LEFT JOIN  Students S
ON S.StudentID = G.ID 

--RIGHT JOIN
SELECT S.NAME,S.GENDER,S.AGE,G.NAME
FROM GENDER G
RIGHT JOIN Students S
ON S.StudentID = G.ID 

--FULL JOIN
SELECT S.NAME,S.GENDER,S.AGE,G.NAME
FROM GENDER G
FULL JOIN Students S
ON S.StudentID = G.ID 

--CROSS JOIN
SELECT S.NAME,S.GENDER,S.AGE,G.NAME
FROM GENDER G
CROSS JOIN Students S
 