IF EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'Students')
    DROP TABLE Students

CREATE TABLE Students(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME VARCHAR(20),
GENDER VARCHAR(10),
AGE INT
)

INSERT INTO Students
SELECT 'MUKUL','MALE',24
UNION
SELECT 'RAMU','MALE',25
UNION
SELECT 'MERCY','FEMALE',23
UNION
SELECT 'ARANI','FEMALE',22
UNION
SELECT 'RAHUL','MALE',26
UNION
SELECT 'ANNY','FEMALE',21

GO

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'MARKS')
  DROP TABLE MARKS

CREATE TABLE MARKS(
ID INT PRIMARY KEY IDENTITY(1,1),
STUDENTSID INT FOREIGN KEY REFERENCES Students(ID),
SUBJECTNAME VARCHAR(10),
MARKS INT
)

INSERT INTO MARKS
SELECT 1,'SCIENCE',45
UNION
SELECT 1,'MATHS',78
UNION
SELECT 1,'ENGLISH',67
UNION
SELECT 2,'SCIENCE',47
UNION
SELECT 2,'MATHS',67
UNION
SELECT 2,'ENGLISH',56
UNION
SELECT 3,'SCIENCE',74
UNION
SELECT 3,'MATHS',73
UNION
SELECT 3,'ENGLISH',63
UNION
SELECT 4,'SCIENCE',56
UNION
SELECT 4,'MATHS',78
UNION
SELECT 4,'ENGLISH',58
UNION
SELECT 5,'SCIENCE',78
UNION
SELECT 5,'MATHS',88
UNION
SELECT 5,'ENGLISH',59
UNION
SELECT 6,'SCIENCE',72
UNION
SELECT 6,'MATHS',60
UNION
SELECT 6,'ENGLISH',64


SELECT * FROM Students
SELECT * FROM MARKS

--==========================================
USER DEFINED FUNCTIONS

1) SCALAR FUNCTION
2) INLINE TABLE VALUED FUNCTION
3) MULTILINE TABLE VALUED FUNCTION

--CREATING SCALAR FUNCTION

CREATE FUNCTION udf_GetStudentAvgMarks(
   @ID int
   )
RETURNS INT
AS
BEGIN
  DECLARE @AVG INT
  SELECT @AVG = AVG(MARKS)
  FROM MARKS
  WHERE ID = @ID

RETURN @AVG
END

SELECT  dbo.udf_GetStudentAvgMarks(4)

--CREATING INLINE TABLE VALUED FUNCTION

CREATE FUNCTION udf_GetStudentTotalMarks(
 @ID INT)
RETURNS TABLE
AS
RETURN
SELECT ID,SUM(MARKS) TOTALMARKS
FROM MARKS
WHERE ID = @ID
GROUP BY ID

SELECT * FROM dbo. udf_GetStudentTotalMarks(2)

--CREATING MULTILINE FUNCTION

CREATE FUNCTION udf_GetMarksAvgMarks(
@ID INT
)
RETURNS @RESULTTABLE TABLE
(
ID INT,NAME VARCHAR(20)
)
AS
BEGIN
  INSERT INTO @RESULTTABLE
  SELECT ID, AVG(MARKS) AVG_MARKS
  FROM MARKS
  WHERE ID = @ID
  GROUP BY ID
RETURN
END

GO
 
 SELECT * FROM dbo.udf_GetMarksAvgMarks(3)