VIEW : A VIEW IN SQL SERVER IS LIKE A VERTUAL TABLE THAT CONTAINS  DATA FROM ONE OR MORE TABLE.
       THERE ARE TWO TYPES OF VIEWS SIMPLE AND COMPLEX VIEWS.
	   WE CAN DO DML OPERATIONS IN SIMPLE VIEW BUT NOT IN OTHER OPERATIORS.

CREATE TABLE GENDER
(
GENDERID INT PRIMARY KEY,
GENDERNAME VARCHAR(10)
)

INSERT INTO GENDER(GENDERID,GENDERNAME)
SELECT 1,'MALE'
UNION 
SELECT 2,'FEMALE'

CREATE TABLE BRANCH
(
BRANCHID INT PRIMARY KEY,
BRANCHNAME VARCHAR(20)
)

INSERT INTO BRANCH(BRANCHID,BRANCHNAME)
SELECT 1,'CSE'
UNION
SELECT 2,'ECE'


CREATE TABLE STUDENTS
(
STUDENTID INT PRIMARY KEY,
STUDENTNAME VARCHAR(30),
AGE INT,
GENDERID INT FOREIGN KEY REFERENCES GENDER(GENDERID),
BRANCHID INT FOREIGN KEY REFERENCES BRANCH(BRANCHID)
)


INSERT INTO STUDENTS(STUDENTID,STUDENTNAME,AGE,GENDERID,BRANCHID)
SELECT 1,'RAMU',22,1,1
UNION 
SELECT 2,'SUMAN',20,2,2
UNION
SELECT 3,'SAM',23,1,1
UNION 
SELECT 4,'RAKUL',19,2,2
UNION
SELECT 5,'RANI',21,2,1
UNION
SELECT 6,'DEEPAK',24,1,2

SELECT * FROM STUDENTS
SELECT * FROM GENDER
SELECT * FROM BRANCH

IF EXISTS (SELECT * FROM SYS.VIEWS WHERE NAME = 'V_STUDENTSDETAILS')
BEGIN
   DROP VIEW V_STUDENTDETAILS
END
GO
CREATE VIEW vw_STUDENTSDETAILS
AS
SELECT S.STUDENTID,S.STUDENTNAME,G.GENDERNAME,B.BRANCHNAME
FROM STUDENTS S
INNER JOIN GENDER G ON S.GENDERID = G.GENDERID
INNER JOIN BRANCH B ON S.GENDERID = B.BRANCHID

SELECT * FROM vw_STUDENTSDETAILS

CREATE VIEW vw_StudentDetails_1
AS
SELECT STUDENTID,STUDENTNAME,AGE
FROM STUDENTS

SELECT * FROM vw_StudentDetails_1

update vw_StudentDetails_1
set STUDENTNAME = 'RAHUL'
WHERE STUDENTID = 1

UPDATE  STUDENTS
SET STUDENTNAME = 'RAHUL'
WHERE STUDENTID = 1

INSERT INTO vw_StudentDetails_1 (STUDENTID,STUDENTNAME,AGE)
SELECT 7,'SHIKHA'24

SELECT * FROM Production.Products
SELECT * FROM Production.Categories
SELECT * FROM Production.Suppliers

CREATE VIEW vw_ProductionDetails
AS
SELECT p.productname,p.unitprice,c.categoryname,c.description,s.companyname,s.contactname,s.contacttitle
FROM Production.Products P
INNER JOIN Production.Categories c ON p.productid = c.categoryid
INNER JOIN Production.Suppliers S ON p.productid = s.supplierid

SELECT * FROM vw_ProductionDetails

--CREATING VIEW WITH SCHEMABINDING
CREATE VIEW vw_ProductionDetailswith
WITH SCHEMABINDING
AS
SELECT p.productname,p.unitprice,c.categoryname,c.description,s.companyname,s.contactname,s.contacttitle
FROM Production.Products P
INNER JOIN Production.Categories c ON p.productid = c.categoryid
INNER JOIN Production.Suppliers S ON p.productid = s.supplierid

SP_HELPTEXT vw_ProductionDetailswith --to get details of view table

--CREATING VIEW WITH ENCRYPTION

CREATE VIEW vw_ProductionDetailsency
WITH ENCRYPTION
AS
SELECT p.productname,p.unitprice,c.categoryname,c.description,s.companyname,s.contactname,s.contacttitle
FROM Production.Products P
INNER JOIN Production.Categories c ON p.productid = c.categoryid
INNER JOIN Production.Suppliers S ON p.productid = s.supplierid

SELECT * FROM vw_ProductionDetailsency

sp_helptext vw_ProductionDetailsency
